// <auto-generated />
using BluetoothTempEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BluetoothTempEntities.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221103162653_try2")]
    partial class try2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30");

            modelBuilder.Entity("BluetoothTempEntities.BluetoothDeviceWasСonnected", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsAutoconnect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsNfcWrited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BluetoothDevicesWasСonnected");
                });
#pragma warning restore 612, 618
        }
    }
}
